### ISSUE TITLE
Chinese will show garbled

### ISSUE THREAD

**Issue by niulinlnc** [Pravithavarghese1/hr_biometric_machine#16]
When my attendance machine staff name is Chinese, will show garbled.
![default](https://user-images.githubusercontent.com/11767049/29511443-d15074ea-8691-11e7-9311-cab7e7b1a4e9.png)

**Comment by Pravithavarghese1** [comment]
I think you should pass the user language while creating and writing attendance.

**Comment by niulinlnc** [comment]
Thank you,
I have solved this problem.
Add to:
import sys
reload (sys)
sys.setdefaultencoding ('gbk')

**Comment by Pravithavarghese1** [comment]
Good to know you solved the issue. Thankyou for updating.
